version: "3.8"

services:      
  using-env-variables:
    image: using-env-variables
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8686:80
    environment: 
      - GC-TOKEN=""
#      - GC-TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ijk2MWM1YmM1LWJkM2EtNDg4MS1iMmI0LTgyM2YzOGM0YzBiYyJ9.eyJ0eXBlIjoidXNlciIsImNpZCI6ImFjYWQyNjNmLTNlYzctNGVkZS05MTFmLTIzZjEyODYwZGEwYSIsImVtYWlsIjoia3lsZS5yb2dlcnNAZ21haWwuY29tIiwidXNlcklkIjoiMzZiZTgwYWMtY2UwZC00OTE4LTgzMDYtY2M2MjMzOTZlMmMyIiwicnRrbiI6IjIxNmI3N2NkLWIwODctNDA3YS05ZmRhLWNjZTU1MzNmNGY4Yzo5ODRjOWUzYi1iOTI5LTQ3ZDQtYWEwZi0xOTJkYTIyOTMwZjkiLCJpYXQiOjE2NTI3ODk4ODYsImV4cCI6MTY1MjgzMzA4Nn0.8pc0sGIY377Uc9aXSSiLaQL1Zwroy0KmWzzL1iX1AW8"